### ISSUE TITLE
feat:🎁 tree-sitter injections

### ISSUE THREAD

**Issue by molostovvs** [GustavEikaas/easy-dotnet.nvim#151]
Hi, I want to write tree-sitter language injections to work with sql, json and xml strings that are in a .cs file. Like for example in this plugin https://github.com/ray-x/go.nvim/tree/master/after/queries/go.

What do you think about including them in your plugin? 
I'm planning to make an analog of language injections like in Rider https://www.jetbrains.com/help/rider/Language_Injections.html#use-comments
so that this sql string will be correctly highlighted:

```cs
//language=sql
var someQuery = "select * from user where id = 0";
```

with fallback options that will work based on regexp.

## Implementation

test c# project with some strings: https://github.com/molostovvs/TreeSitterCsharpInjectionsTestProject

### todo:

- [x] need to discuss the use of regexp string detection, since if there is a bug in such detection, there is no easy way to disable such injection
- [x] need to discuss the importance of having examples for queries. Perhaps a text description will be enough. it will reduce the number of lines in the file and improve its readability
- [x] need to discuss the importance of having queries to inject json and xml into quoted and verbatim strings (single line), since often strings with xml or json inside are multi-line
- [x] discuss whether it is necessary to implement language injections for sql providers, like in this config for example https://github.com/TheLeoP/nvim-config/blob/ed60cfe29f009711555b763cfc6e1e7e4091ef8f/queries/c_sharp/injections.scm

#### strings

| string          | sql | json | xml |
|-----------------|-----|------|-----|
| quoted          | ✅  | :question: | ✅ |
| verbatim        | ✅  | :question: | ✅ |
| raw             | ✅  | ✅   | ✅  |
| regexp quoted   | ❌  | ❌   | ❌  |
| regexp verbatim | ❌  | ❌   | ❌  |
| regexp raw      | ❌  | ❌   | ❌  |

> - quoted and verbatim json strings implementation is complicated and as I think has little value, so I didn't implement it
> - quoted and verbatim xml strings were cheap to implement (parsed documents a bit buggy, but highlighting works)

#### interpolated strings

| interpolated string | json | xml |
|---------------------|------|-----|
| quoted              | :x:  | :x: |
| verbatim            | :x:  | :x: |
| raw                 | ✅   | ✅   |
| regexp quoted       | ❌   | ❌   |
| regexp verbatim     | ❌   | ❌   |
| regexp raw          | ❌   | ❌   |

**Comment by GustavEikaas** [comment]
That would be awesome! Its definitely something that would be cool to have included in this plugin

**Comment by molostovvs** [comment]
Hi, @GustavEikaas!

I've prepared a PR that addresses the functionality outlined in the table (highlighting for SQL, JSON, and XML in strings). The PR is ready for merging, and it covers all the use cases marked with checkmarks.

However, there are a few topics I'd like to discuss for future improvements, which could be handled in subsequent or this PR:

- Regex-based string detection: Should we use regex for detecting certain string patterns? If there’s a bug in this detection, it may be tricky to disable the injection easily. What are your thoughts on this approach? I think simple rules can be written without bugs, as for example it is done in a plugin for Go for [strings with sql](https://github.com/ray-x/go.nvim/blob/12ab6ac0fdd03b1ec9ee4e5378dd204f744a55bf/after/queries/go/injections.scm#L29).
- Examples for queries: Currently, I've written examples for the injections in `.scm` file, but I think a text description might be sufficient. This would reduce the number of lines and improve file readability.
- JSON injections for single-line strings: I've not implemented injections for quoted and verbatim JSON strings due to the complexity and what I see as limited value.
- SQL providers: It might be useful to add injections for strings used in SQL providers as well, similar to [this config](https://github.com/TheLeoP/nvim-config/blob/ed60cfe29f009711555b763cfc6e1e7e4091ef8f/queries/c_sharp/injections.scm).

Lastly, do you think we should close this issue after merging, or should we leave it open and update the scope of work for further improvements?

I'm happy to adjust things based on your feedback.

Thanks!

**Comment by GustavEikaas** [comment]
> Regex-based string detection
This touches upon my first thought when testing out the PR, it works out of the box without any configuration. Which is always a scary thing. I'm assuming there is not an easy way to dynamically register the queries? If there is not then we should be careful with potentially complex logic. It would be a shame to introduce a bug to users who have no conscious relation to this feature

> Examples for queries
To a dev unfamiliar with TS queries it was nice to see examples in the file but I have no strong feelings for or against this. You have worked more with this type of functionality than me so you should be better suited to answer this question as its a preference thing

> JSON injections for single-line string
This initial PR is above and beyond my expectations and I think the consumers will see every improvement as a plus. Referring to discussion point 1. Lets not introduce too much complexity initially

> SQL providers
If you feel motivated to implement more sql providers after merging this PR go ahead, but if not then dont sweat it. 


I think the work you have done here is amazing and I feel comfortable approving the PR at this stage. I think its important to not overcomplicate things. Testing this initial functionality on actual users will hopefully give us a broader perspective on the value it provides


Awesome work!❤
